# Deployment 配置
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1  # 支持多副本
  selector:
    matchLabels:
      app: my-app1
  template:
    metadata:
      labels:
        app: my-app1
    spec:
    nodeSelector:
        node.kubernetes.io/instance-type:  <node_ip1>
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
# Deployment 配置
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment2
spec:
  replicas: 1  # 支持多副本
  selector:
    matchLabels:
      app: my-app2
  template:
    metadata:
      labels:
        app: my-app2
    spec:
    nodeSelector:
        node.kubernetes.io/instance-type:  <node_ip2>
      containers:
      - name: nginx2
        image: nginx:latest
        ports:
        - containerPort: 80
