apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  nodeName: <node_ip1>  # 直接指定节点名称（需精确匹配）
  containers:
  - name: nginx
    image: nginx:1.21
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod2
  labels:
    app: nginx2
spec:
  nodeName: <node_ip2>  # 直接指定节点名称（需精确匹配）
  containers:
  - name: nginx2
    image: nginx:1.21
    ports:
    - containerPort: 80
